const Constants = {
    SET_QUIZE_API : 'SET_QUIZE_API',
    SET_QUIZE_API_LOADER:'SET_QUIZE_API_LOADER',
    GET_PARTICULAR_QUIZ:'GET_PARTICULAR_QUIZ',
    SAVE_ANSWER_WITH_QUESTION_NUMBER:"SAVE_ANSWER_WITH_QUESTION_NUMBER",
    SUBMIT_POST_RESPONSE:'SUBMIT_POST_RESPONSE',
}
export default Constants;