export const contactdetails = [
    {
      Fullname : "Micky Huston",
      firstname : "Micky",
      lastname : "Huston",
      Email : "mickyhuston@live.com",
      Phone : "0692384567",
      company : "Project Manager in Data Analyst Team",
      Address : "47 west berinlin road germany",
      Notice : "Tax Evasion and Payout Notice",
      dataletters: "MH",
      color:"#FFA500",
      Date: "27 Mar 2017 10:00am",
      id:1
    },
    {
        Fullname : "Kaviya Bakiyavel",
        Email : "kaviybaki@gmail.com",
        firstname : "Kaviya",
        lastname : "Bakiyavel",
        Phone : "9790304313",
        company : "Senvion India Private Limted",
        Address : "ITPL Bangalore",
        Notice : "Tax Evasion and Payout Notice",
        dataletters: "KB",
        color:"#FF0000",
        Date: "27 Mar 2017 10:00am",
        id:2
    },
    {
        Fullname : "John",
        Email : "John@gmail.com",
        firstname : "John",
        lastname : "",
        Phone : "6286278395",
        company : "No information provided",
        Address : "47 west berinlin road germany",
        Notice : "Tax Evasion and Payout Notice",
        dataletters: "J",
        color:"#FF00FF",
        Date: "27 Mar 2017 10:00am",
        id:3
    },
    {
        Fullname : "Donald Trump",
        Email : "Donaldtrump@gmail.com",
        firstname : "Donald",
        lastname : "Trump",
        Phone : "2568253899",
        company : "No information provided",
        Address : "White house USA",
        Notice : "No Tax",
        dataletters: "DT",
        color:"#C0C0C0",
        Date: "27 Mar 2017 10:00am",
        id:4
    },
    {
        Fullname : "Narendra Modi",
        Email : "narendra modi@gmail.com",
        firstname : "Narendra",
        lastname : "Modi",
        Phone : "5467284567",
        company : " Government of India",
        Address : "Delhi",
        Notice : "No Tax",
        dataletters: "NM",
        color:"#ADD8E6",
        Date: "27 Mar 2017 10:00am",
        id:5
    },
    {
        Fullname : "Mark Zuckerberg",
        Email : "markzuckerberg@gmail.com",
        firstname : "Mark",
        lastname : "Zuckerberg",
        Phone : "3437124914",
        company : "CEO Facebook",
        Address : "California USA",
        Notice : "Tax Evasion and Payout Notice",
        dataletters: "MZ",
        color:"#0000A0",
        Date: "27 Mar 2017 10:00am",
        id:5
    },
    {
        Fullname : "Charlie Chaplin",
        Email : "charliechaplin@gmail.com",
        firstname : "Charlie",
        lastname : "Chaplin",
        Phone : "1237283215",
        company : "comic actor",
        Address : "In Heaven",
        Notice : "--",
        dataletters: "CC",
        color:"#008000",
        Date: "27 Mar 2017 10:00am",
        id:6
    },
    {
        Fullname : "Kalpana Chawla",
        Email : "kalpanachawla@gmail.com",
        firstname : "Kalpana",
        lastname : "Chawla",
        Phone : "3437124931",
        company : "Astronaut",
        Address : "USA",
        Notice : "--",
        dataletters: "KC",
        color:"#800000",
        Date: "27 Mar 2017 10:00am",
        id:7
    },
    {
        Fullname : "A. P. J. Abdul Kalam",
        Email : "abdulkalam@gmail.com",
        firstname : "Abdul",
        lastname : "Kalam",
        Phone : "2312848143",
        company : "Former President of India and  Indian aerospace scientist ",
        Address : "Rameswaram",
        Notice : "--",
        dataletters: "AK",
        color:"#808000",
        Date: "27 Mar 2017 10:00am",
        id:8
    },
]